//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempsDeParole
{
   using System;
   using System.Collections.Generic;
   using System.Data.Entity;

   public partial class Animateurs
    {
        public int id { get; set; }
        public string name { get; set; }
        public long diffTimeSpokenMs { get; set; }
        public long timeSpokenMs { get; set; }

      public static implicit operator DbSet<object>(Animateurs v)
      {
         throw new NotImplementedException();
      }
   }
}
